---
services:
  calibre:
    image: lscr.io/linuxserver/calibre:6.7.1
    container_name: calibre
    security_opt:
      - seccomp=unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /mnt/RAID/public/eBooks:/config
    restart: unless-stopped

networks:
  default:
    external: true
    name: calibre
